// Public endpoints used by the storefront.
import { Router } from "express";
import { all, getSettings, productFromRow } from "../db.js";
import { createOrder, getOrder, slotsFor, OrderError } from "../orders.js";
import { rateLimit } from "../auth.js";
import { STATUSES } from "../permissions.js";

export function publicRoutes({ testimonials }) {
  const router = Router();

  // The storefront's catalog, generated from the database on each request so
  // prices, stock and settings changed in the admin panel show up immediately.
  router.get("/js/data.js", (_req, res) => {
    const s = getSettings();
    const categories = all("SELECT id, ne, en, image FROM categories ORDER BY sort, en");
    const products = all("SELECT * FROM products WHERE active = 1 ORDER BY id").map(productFromRow)
      .map(({ lowStock, active, updatedAt, ...p }) => p);
    const shop = {
      FREE_DELIVERY_OVER: s.free_delivery_over,
      STANDARD_FEE: s.standard_fee,
      EXPRESS_FEE: s.express_fee,
      TAX_RATE: s.tax_rate,
      EXPRESS_CUTOFF_HOUR: s.express_cutoff_hour,
      PHONE: s.phone,
      EMAIL: s.email,
      ACCEPTING_ORDERS: s.accepting_orders,
      SLOTS: {
        standard: slotsFor("standard").map((x) => x.label),
        expressToday: slotsFor("express_today").map((x) => x.label),
        expressTomorrow: slotsFor("express_tomorrow").map((x) => x.label),
      },
    };
    const json = (v) => JSON.stringify(v).replace(/</g, "\\u003c");
    res.type("application/javascript").set("Cache-Control", "no-store").send(
      `// Generated by the Sagpat server from the database.\n` +
      `const CATEGORIES = ${json(categories)};\n` +
      `const PRODUCTS = ${json(products)};\n` +
      `const TESTIMONIALS = ${json(testimonials)};\n` +
      `const SHOP_SETTINGS = ${json(shop)};\n` +
      `function getProduct(id) { return PRODUCTS.find((p) => p.id === Number(id)); }\n` +
      `function getCategory(id) { return CATEGORIES.find((c) => c.id === id); }\n`,
    );
  });

  router.post("/api/orders", rateLimit({ key: "order", max: 20, windowMs: 10 * 60 * 1000 }), (req, res) => {
    try {
      const order = createOrder(req.body);
      res.status(201).json(publicOrder(order));
    } catch (err) {
      if (err instanceof OrderError) return res.status(err.status).json({ error: err.message });
      throw err;
    }
  });

  // Customers can view their own order with the private key from the confirmation link
  router.get("/api/orders/:id", (req, res) => {
    const order = getOrder(String(req.params.id));
    if (!order || order.accessKey !== String(req.query.key || "")) return res.status(404).json({ error: "Order not found." });
    res.json(publicOrder(order));
  });

  return router;
}

function publicOrder(o) {
  return {
    id: o.id,
    key: o.accessKey,
    createdAt: o.createdAt,
    status: o.status,
    statusLabel: STATUSES[o.status],
    customer: o.customer,
    delivery: o.delivery,
    payment: o.payment,
    totals: o.totals,
    items: o.items,
    // Customers see status changes, not internal staff notes or names
    history: o.events.filter((e) => e.type === "status").map((e) => ({ at: e.at, status: e.status, label: STATUSES[e.status] })),
  };
}
